"""initial schema

Revision ID: d4b7ffff8d1f
Revises: 
Create Date: 2026-09-19 19:46:21.060472

"""
from typing import Sequence, Union

from alembic import op
import fastapi_users_db_sqlalchemy.generics
import sqlalchemy as sa


TABLES = ("puzzles", "users", "games", "game_attempts", "game_moves", "alembic_version")

# revision identifiers, used by Alembic.
revision: str = 'd4b7ffff8d1f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puzzles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('random', 'daily', name='puzzle_kind'), nullable=False),
    sa.Column('daily_date', sa.Date(), nullable=True),
    sa.Column('start_player_id', sa.Integer(), nullable=False),
    sa.Column('end_player_id', sa.Integer(), nullable=False),
    sa.Column('optimal_hops', sa.SmallInteger(), nullable=False),
    sa.Column('optimal_path', sa.JSON(), nullable=False),
    sa.Column('graph_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'daily_date')
    )
    op.create_table('users',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('games',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('puzzle_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'won', 'abandoned', name='game_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hops', sa.SmallInteger(), nullable=True),
    sa.Column('efficiency', sa.Float(), nullable=True),
    sa.Column('rarity', sa.Float(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['puzzle_id'], ['puzzles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_games_puzzle_score', 'games', ['puzzle_id', 'score'], unique=False)
    op.create_index('ix_games_user_started', 'games', ['user_id', 'started_at'], unique=False)
    op.create_table('game_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_attempts_game_id'), 'game_attempts', ['game_id'], unique=False)
    op.create_table('game_moves',
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('idx', sa.SmallInteger(), nullable=False),
    sa.Column('from_player_id', sa.Integer(), nullable=False),
    sa.Column('to_player_id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('seasons', sa.JSON(), nullable=False),
    sa.Column('rarity', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'idx')
    )
    # ### end Alembic commands ###

    # Supabase exposes the public schema over its REST API (PostgREST). With RLS on and no policies, the anon /
    # authenticated API roles can't read or write these tables; our backend connects as the table owner, which
    # bypasses RLS.
    if op.get_bind().dialect.name == "postgresql":
        for table in TABLES:
            op.execute(f'ALTER TABLE "{table}" ENABLE ROW LEVEL SECURITY')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_moves')
    op.drop_index(op.f('ix_game_attempts_game_id'), table_name='game_attempts')
    op.drop_table('game_attempts')
    op.drop_index('ix_games_user_started', table_name='games')
    op.drop_index('ix_games_puzzle_score', table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('puzzles')
    # ### end Alembic commands ###
    sa.Enum(name='game_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='puzzle_kind').drop(op.get_bind(), checkfirst=True)
